# Generated by Django 6.0.1 on 2026-06-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_alumnos_options_alumnos_carrera_alumnos_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
